name: Gradle build

on:
  push:
    branches: [ "1.19" ]
  pull_request:
    branches: [ "1.19" ]

jobs:
  build:
    name: Checkout latest commit and build mod with Gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 17
          distribution: adopt
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.2.2
        with:
          cache-disabled: false
          arguments: build
